### ISSUE TITLE
Breaks if a trackpoint is missing an <ele> element.

### ISSUE THREAD

**Issue by HDv2b** [timbenniks/gpx-for-runners#2]
Some apps (eg. Endomondo) will output .gpx files and not necessarily include elevation data for every single point.

Guessing a conditional inside `createJsonFromGpxDom()` would do the trick but currently struggling to get the build script to work..

**Comment by timbenniks** [comment]
Hi @ElGoorf thanks for your bug report. I only tested with Garmin and Strava GPX files. I'll have a look at the Endomondo output as well.

**Comment by HDv2b** [comment]
Sample output:

`<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="Endomondo.com" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/GpxExtensions/v3 http://www.garmin.com/xmlschemas/GpxExtensionsv3.xsd http://www.garmin.com/xmlschemas/TrackPointExtension/v1 http://www.garmin.com/xmlschemas/TrackPointExtensionv1.xsd" xmlns="http://www.topografix.com/GPX/1/1" xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1" xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <metadata>
    <author>
      <name>Redacted</name>
      <email id="my.email" domain="gmail.com"/>
    </author>
    <link href="http://www.endomondo.com">
      <text>Endomondo</text>
    </link>
    <time>2016-11-01T13:40:45Z</time>
  </metadata>
  <trk>
    <name>Stirling to Edinburgh</name>
    <cmt>National Cycle Network&apos;s a bit messy in this area...</cmt>
    <src>http://www.endomondo.com/</src>
    <link href="https://www.endomondo.com/users/1048867/workouts/9486206">
      <text>Stirling to Edinburgh</text>
    </link>
    <type>CYCLING_TRANSPORTATION</type>
    <trkseg>
      <trkpt lat="56.115702" lon="-3.934264">
        <time>2011-04-22T12:06:48Z</time>
      </trkpt>
      <trkpt lat="56.115702" lon="-3.934264">
        <time>2011-04-22T12:06:59Z</time>
      </trkpt>
    </trkseg>
    <trkseg>
      <trkpt lat="56.115702" lon="-3.934264">
        <time>2011-04-22T12:07:02Z</time>
      </trkpt>
      <trkpt lat="56.11567" lon="-3.934162">
        <ele>83.0</ele>
        <time>2011-04-22T12:07:18Z</time>
      </trkpt>
      <trkpt lat="56.115884" lon="-3.933932">
        <ele>76.0</ele>
        <time>2011-04-22T12:07:29Z</time>
      </trkpt>
      <trkpt lat="56.11597" lon="-3.933932">
        <ele>76.0</ele>
        <time>2011-04-22T12:07:33Z</time>
      </trkpt>
      <trkpt lat="56.116313" lon="-3.93427">
        <ele>78.0</ele>
        <time>2011-04-22T12:07:42Z</time>
      </trkpt>
      <trkpt lat="56.116415" lon="-3.934302">
        <ele>77.0</ele>
        <time>2011-04-22T12:07:44Z</time>
      </trkpt>
      <trkpt lat="56.116866" lon="-3.934581">
        <ele>81.0</ele>
        <time>2011-04-22T12:07:53Z</time>
      </trkpt>
      <trkpt lat="56.116866" lon="-3.934581">
        <time>2011-04-22T12:08:05Z</time>
      </trkpt>
    </trkseg>
    <trkseg>
      <trkpt lat="56.116866" lon="-3.934581">
        <time>2011-04-22T12:08:05Z</time>
      </trkpt>
      <trkpt lat="56.117907" lon="-3.934532">
        <ele>81.0</ele>
        <time>2011-04-22T12:08:12Z</time>
      </trkpt>
      <trkpt lat="56.118647" lon="-3.935203">
        <ele>86.0</ele>
        <time>2011-04-22T12:08:24Z</time>
      </trkpt>
      <trkpt lat="56.119151" lon="-3.9356">
        <ele>82.0</ele>
        <time>2011-04-22T12:08:32Z</time>
      </trkpt>
      <trkpt lat="56.119285" lon="-3.93582">
        <ele>84.0</ele>
        <time>2011-04-22T12:08:37Z</time>
      </trkpt>
      <trkpt lat="56.119462" lon="-3.935573">
        <ele>84.0</ele>
        <time>2011-04-22T12:08:43Z</time>
      </trkpt>
      <trkpt lat="56.119457" lon="-3.935278">
        <ele>80.0</ele>
        <time>2011-04-22T12:08:48Z</time>
      </trkpt>
      <trkpt lat="56.119237" lon="-3.934768">
        <ele>75.0</ele>
        <time>2011-04-22T12:08:57Z</time>
      </trkpt>
      <trkpt lat="56.119237" lon="-3.934768">
        <time>2011-04-22T12:09:09Z</time>
      </trkpt>
    </trkseg>
    <trkseg>
      <trkpt lat="56.119237" lon="-3.934768">
        <time>2011-04-22T12:09:17Z</time>
      </trkpt>
      <trkpt lat="56.119307" lon="-3.934962">
        <ele>74.0</ele>
        <time>2011-04-22T12:09:20Z</time>
      </trkpt>
      <trkpt lat="56.119307" lon="-3.934962">
        <time>2011-04-22T12:09:32Z</time>
      </trkpt>
    </trkseg>
    <trkseg>
      <trkpt lat="56.119307" lon="-3.934962">
        <time>2011-04-22T12:09:41Z</time>
      </trkpt>
      <trkpt lat="56.119307" lon="-3.934962">
        <time>2011-04-22T12:09:53Z</time>
      </trkpt>
    </trkseg>
    <trkseg>
      <trkpt lat="56.119307" lon="-3.934962">
        <time>2011-04-22T12:10:10Z</time>
      </trkpt>
      <trkpt lat="56.119248" lon="-3.934543">
        <ele>78.0</ele>
        <time>2011-04-22T12:10:14Z</time>
      </trkpt>
      <trkpt lat="56.119264" lon="-3.934425">
        <ele>78.0</ele>
        <time>2011-04-22T12:10:18Z</time>
      </trkpt>
      <trkpt lat="56.119376" lon="-3.934119">
        <ele>73.0</ele>
        <time>2011-04-22T12:10:29Z</time>
      </trkpt>
      <trkpt lat="56.119382" lon="-3.933991">
        <ele>73.0</ele>
        <time>2011-04-22T12:10:33Z</time>
      </trkpt>
      <trkpt lat="56.119419" lon="-3.933878">
        <ele>76.0</ele>
        <time>2011-04-22T12:10:39Z</time>
      </trkpt>
      <trkpt lat="56.11943" lon="-3.933755">
        <ele>77.0</ele>
        <time>2011-04-22T12:10:43Z</time>
      </trkpt>
      <trkpt lat="56.119478" lon="-3.933679">
        <ele>76.0</ele>
        <time>2011-04-22T12:10:47Z</time>
      </trkpt>
      <trkpt lat="56.119494" lon="-3.933561">
        <ele>75.0</ele>
        <time>2011-04-22T12:10:50Z</time>
      </trkpt>
      <trkpt lat="56.119564" lon="-3.933363">
        <ele>75.0</ele>
        <time>2011-04-22T12:10:57Z</time>
      </trkpt>
      <trkpt lat="56.119537" lon="-3.933218">
        <ele>76.0</ele>
        <time>2011-04-22T12:11:01Z</time>
      </trkpt>
      <trkpt lat="56.119537" lon="-3.933218">
        <time>2011-04-22T12:11:13Z</time>
      </trkpt>
    </trkseg>
    <trkseg>
      <trkpt lat="56.119537" lon="-3.933218">
        <time>2011-04-22T12:11:13Z</time>
      </trkpt>
      <trkpt lat="56.119537" lon="-3.933218">
        <time>2011-04-22T12:11:25Z</time>
      </trkpt>
    </trkseg>
    <trkseg>
      <trkpt lat="56.119537" lon="-3.933218">
        <time>2011-04-22T12:11:30Z</time>
      </trkpt>
      <trkpt lat="56.119537" lon="-3.933218">
        <time>2011-04-22T12:11:42Z</time>
      </trkpt>
    </trkseg>
    <trkseg>
      <trkpt lat="56.119537" lon="-3.933218">
        <time>2011-04-22T12:11:46Z</time>
      </trkpt>
      <trkpt lat="56.119232" lon="-3.932827">
        <ele>73.0</ele>
        <time>2011-04-22T12:11:49Z</time>
      </trkpt>
      <trkpt lat="56.119167" lon="-3.932719">
        <ele>73.0</ele>
        <time>2011-04-22T12:11:52Z</time>
      </trkpt>
      <trkpt lat="56.119044" lon="-3.93192">
        <ele>76.0</ele>
        <time>2011-04-22T12:12:08Z</time>
      </trkpt>
      <trkpt lat="56.119017" lon="-3.931282">
        <ele>75.0</ele>
        <time>2011-04-22T12:12:20Z</time>
      </trkpt>
      <trkpt lat="56.11884" lon="-3.93096">
        <ele>78.0</ele>
        <time>2011-04-22T12:12:29Z</time>
      </trkpt>
      <trkpt lat="56.11884" lon="-3.93096">
        <time>2011-04-22T12:12:41Z</time>
      </trkpt>
    </trkseg>
    <trkseg>
      <trkpt lat="56.11884" lon="-3.93096">
        <time>2011-04-22T12:13:19Z</time>
      </trkpt>
      <trkpt lat="56.118556" lon="-3.9303">
        <ele>73.0</ele>
        <time>2011-04-22T12:13:32Z</time>
      </trkpt>
      <trkpt lat="56.118427" lon="-3.930058">
        <ele>72.0</ele>
        <time>2011-04-22T12:13:36Z</time>
      </trkpt>
      <trkpt lat="56.118282" lon="-3.929898">
        <ele>74.0</ele>
        <time>2011-04-22T12:13:39Z</time>
      </trkpt>
      <trkpt lat="56.118105" lon="-3.929667">
        <ele>73.0</ele>
        <time>2011-04-22T12:13:43Z</time>
      </trkpt>
      <trkpt lat="56.118003" lon="-3.92942">
        <ele>71.0</ele>
        <time>2011-04-22T12:13:47Z</time>
      </trkpt>
      <trkpt lat="56.118068" lon="-3.929093">
        <ele>69.0</ele>
        <time>2011-04-22T12:13:51Z</time>
      </trkpt>
      <trkpt lat="56.118191" lon="-3.928798">
        <ele>70.0</ele>
        <time>2011-04-22T12:13:55Z</time>
      </trkpt>
      <trkpt lat="56.118368" lon="-3.928267">
        <ele>71.0</ele>
        <time>2011-04-22T12:14:03Z</time>
      </trkpt>
      <trkpt lat="56.118443" lon="-3.927982">
        <ele>71.0</ele>
        <time>2011-04-22T12:14:07Z</time>
      </trkpt>
      <trkpt lat="56.118706" lon="-3.927231">
        <ele>70.0</ele>
        <time>2011-04-22T12:14:16Z</time>
      </trkpt>
      <trkpt lat="56.118835" lon="-3.926936">
        <ele>70.0</ele>
        <time>2011-04-22T12:14:20Z</time>
      </trkpt>
      <trkpt lat="56.11921" lon="-3.925778">
        <ele>67.0</ele>
        <time>2011-04-22T12:14:32Z</time>
      </trkpt>
      <trkpt lat="56.119328" lon="-3.925241">
        <ele>67.0</ele>
        <time>2011-04-22T12:14:36Z</time>
      </trkpt>
      <trkpt lat="56.119505" lon="-3.924297">
        <ele>65.0</ele>
        <time>2011-04-22T12:14:44Z</time>
      </trkpt>
      <trkpt lat="56.119548" lon="-3.923793">
        <ele>64.0</ele>
        <time>2011-04-22T12:14:48Z</time>
      </trkpt>
      <trkpt lat="56.119452" lon="-3.922784">
        <ele>67.0</ele>
        <time>2011-04-22T12:14:56Z</time>
      </trkpt>
      <trkpt lat="56.11935" lon="-3.922323">
        <ele>69.0</ele>
        <time>2011-04-22T12:15:00Z</time>
      </trkpt>
      <trkpt lat="56.119232" lon="-3.921899">
        <ele>69.0</ele>
        <time>2011-04-22T12:15:04Z</time>
      </trkpt>
      <trkpt lat="56.118706" lon="-3.920558">
        <ele>72.0</ele>
        <time>2011-04-22T12:15:20Z</time>
      </trkpt>
      <trkpt lat="56.11847" lon="-3.919882">
        <ele>74.0</ele>
        <time>2011-04-22T12:15:28Z</time>
      </trkpt>
      <trkpt lat="56.118282" lon="-3.91911">
        <ele>76.0</ele>
        <time>2011-04-22T12:15:36Z</time>
      </trkpt>
      <trkpt lat="56.1181" lon="-3.918166">
        <ele>76.0</ele>
        <time>2011-04-22T12:15:44Z</time>
      </trkpt>
      <trkpt lat="56.118025" lon="-3.917618">
        <ele>76.0</ele>
        <time>2011-04-22T12:15:49Z</time>
      </trkpt>
      <trkpt lat="56.118019" lon="-3.916867">
        <ele>75.0</ele>
        <time>2011-04-22T12:15:56Z</time>
      </trkpt>
      <trkpt lat="56.118094" lon="-3.915955">
        <ele>74.0</ele>
        <time>2011-04-22T12:16:04Z</time>
      </trkpt>
      <trkpt lat="56.118148" lon="-3.915537">
        <ele>72.0</ele>
        <time>2011-04-22T12:16:08Z</time>
      </trkpt>
      <trkpt lat="56.118164" lon="-3.915076">
        <ele>69.0</ele>
        <time>2011-04-22T12:16:12Z</time>
      </trkpt>
      <trkpt lat="56.118143" lon="-3.914754">
        <ele>69.0</ele>
        <time>2011-04-22T12:16:15Z</time>
      </trkpt>
      <trkpt lat="56.11818" lon="-3.914416">
        <ele>67.0</ele>
        <time>2011-04-22T12:16:19Z</time>
      </trkpt>
      <trkpt lat="56.118175" lon="-3.914003">
        <ele>67.0</ele>
        <time>2011-04-22T12:16:23Z</time>
      </trkpt>
      <trkpt lat="56.118121" lon="-3.913654">
        <ele>66.0</ele>
        <time>2011-04-22T12:16:27Z</time>
      </trkpt>
      <trkpt lat="56.118051" lon="-3.913375">
        <ele>67.0</ele>
        <time>2011-04-22T12:16:32Z</time>
      </trkpt>
      <trkpt lat="56.118051" lon="-3.913375">
        <time>2011-04-22T12:16:43Z</time>
      </trkpt>
    </trkseg>
    <trkseg>
      <trkpt lat="56.118051" lon="-3.913375">
        <time>2011-04-22T12:17:09Z</time>
      </trkpt>
      <trkpt lat="56.117837" lon="-3.913107">
        <ele>69.0</ele>
        <time>2011-04-22T12:17:15Z</time>
      </trkpt>
      <trkpt lat="56.11774" lon="-3.912828">
        <ele>71.0</ele>
        <time>2011-04-22T12:17:19Z</time>
      </trkpt>
      <trkpt lat="56.117569" lon="-3.91197">
        <ele>72.0</ele>
        <time>2011-04-22T12:17:29Z</time>
      </trkpt>
      <trkpt lat="56.117531" lon="-3.91124">
        <ele>73.0</ele>
        <time>2011-04-22T12:17:39Z</time>
      </trkpt>
      <trkpt lat="56.117569" lon="-3.910918">
        <ele>72.0</ele>
        <time>2011-04-22T12:17:43Z</time>
      </trkpt>
      <trkpt lat="56.117494" lon="-3.910462">
        <ele>72.0</ele>
        <time>2011-04-22T12:17:47Z</time>
      </trkpt>
      <trkpt lat="56.11729" lon="-3.910194">
        <ele>71.0</ele>
        <time>2011-04-22T12:17:51Z</time>
      </trkpt>
      <trkpt lat="56.116962" lon="-3.910747">
        <ele>68.0</ele>
        <time>2011-04-22T12:17:58Z</time>
      </trkpt>
      <trkpt lat="56.116871" lon="-3.910865">
        <ele>67.0</ele>
        <time>2011-04-22T12:18:00Z</time>
      </trkpt>
      <trkpt lat="56.116592" lon="-3.911353">
        <ele>67.0</ele>
        <time>2011-04-22T12:18:07Z</time>
      </trkpt>
      <trkpt lat="56.116501" lon="-3.911739">
        <ele>65.0</ele>
        <time>2011-04-22T12:18:11Z</time>
      </trkpt>
      <trkpt lat="56.11649" lon="-3.912055">
        <ele>64.0</ele>
        <time>2011-04-22T12:18:14Z</time>
      </trkpt>
      <trkpt lat="56.116405" lon="-3.91242">
        <ele>63.0</ele>
        <time>2011-04-22T12:18:18Z</time>
      </trkpt>
      <trkpt lat="56.116206" lon="-3.912678">
        <ele>63.0</ele>
        <time>2011-04-22T12:18:23Z</time>
      </trkpt>
      <trkpt lat="56.115949" lon="-3.912742">
        <ele>65.0</ele>
        <time>2011-04-22T12:18:27Z</time>
      </trkpt>
      <trkpt lat="56.115841" lon="-3.912785">
        <ele>65.0</ele>
        <time>2011-04-22T12:18:29Z</time>
      </trkpt>
      <trkpt lat="56.115654" lon="-3.912914">
        <ele>65.0</ele>
        <time>2011-04-22T12:18:33Z</time>
      </trkpt>
      <trkpt lat="56.114699" lon="-3.913423">
        <ele>65.0</ele>
        <time>2011-04-22T12:18:51Z</time>
      </trkpt>
      <trkpt lat="56.114511" lon="-3.913445">
        <ele>65.0</ele>
        <time>2011-04-22T12:18:54Z</time>
      </trkpt>
      <trkpt lat="56.114329" lon="-3.913574">
        <ele>66.0</ele>
        <time>2011-04-22T12:18:58Z</time>
      </trkpt>
      <trkpt lat="56.114055" lon="-3.913676">
        <ele>68.0</ele>
        <time>2011-04-22T12:19:04Z</time>
      </trkpt>
      <trkpt lat="56.113808" lon="-3.913815">
        <ele>68.0</ele>
        <time>2011-04-22T12:19:10Z</time>
      </trkpt>
      <trkpt lat="56.113733" lon="-3.914067">
        <ele>68.0</ele>
        <time>2011-04-22T12:19:14Z</time>
      </trkpt>
      <trkpt lat="56.113583" lon="-3.914126">
        <ele>69.0</ele>
        <time>2011-04-22T12:19:18Z</time>
      </trkpt>
      <trkpt lat="56.112993" lon="-3.914432">
        <ele>69.0</ele>
        <time>2011-04-22T12:19:32Z</time>
      </trkpt>
      <trkpt lat="56.112692" lon="-3.91448">
        <ele>71.0</ele>
        <time>2011-04-22T12:19:38Z</time>
      </trkpt>
      <trkpt lat="56.112258" lon="-3.9147">
        <ele>73.0</ele>
        <time>2011-04-22T12:19:49Z</time>
      </trkpt>
      <trkpt lat="56.112258" lon="-3.9147">
        <time>2011-04-22T12:20:01Z</time>
      </trkpt>
    </trkseg>
    <trkseg>
      <trkpt lat="56.112258" lon="-3.9147">
        <time>2011-04-22T12:20:21Z</time>
      </trkpt>
      <trkpt lat="56.112086" lon="-3.914802">
        <ele>76.0</ele>
        <time>2011-04-22T12:20:26Z</time>
      </trkpt>
      <trkpt lat="56.112038" lon="-3.914673">
        <ele>78.0</ele>
        <time>2011-04-22T12:20:29Z</time>
      </trkpt>
      <trkpt lat="56.111791" lon="-3.91367">
        <ele>83.0</ele>
        <time>2011-04-22T12:20:44Z</time>
      </trkpt>
      <trkpt lat="56.111802" lon="-3.913375">
        <ele>81.0</ele>
        <time>2011-04-22T12:20:48Z</time>
      </trkpt>
      <trkpt lat="56.111839" lon="-3.913112">
        <ele>78.0</ele>
        <time>2011-04-22T12:20:52Z</time>
      </trkpt>
      <trkpt lat="56.111839" lon="-3.913112">
        <time>2011-04-22T12:21:04Z</time>
      </trkpt>
    </trkseg>
  </trk>
</gpx>`

Is it possible you could talk me through the build process? I made some changes to /src/index.js but not sure where to go from there to get the changes to the minified output. `npm run build` outputs some error:

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild gpx-for-runners@1.0.2
6 info build gpx-for-runners@1.0.2
7 verbose unsafe-perm in lifecycle true
8 info gpx-for-runners@1.0.2 Failed to exec build script
9 verbose stack Error: gpx-for-runners@1.0.2 build:`WEBPACK_ENV=build webpack`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid gpx-for-runners@1.0.2
11 verbose cwd F:\Web Dev\gpx-for-runners
12 error Windows_NT 10.0.14393
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v4.4.2
15 error npm  v2.15.0
16 error code ELIFECYCLE
17 error gpx-for-runners@1.0.2 build:`WEBPACK_ENV=build webpack`
17 error Exit status 1
18 error Failed at the gpx-for-runners@1.0.2 build script 'WEBPACK_ENV=build webpack'.
18 error This is most likely a problem with the gpx-for-runners package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     WEBPACK_ENV=build webpack
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs gpx-for-runners
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls gpx-for-runners
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]`

**Comment by timbenniks** [comment]
Hi @ElGoorf, I have resolved the issue for when a trackpoint has no elevation. The code now takes the average elevation of the whole activity for that node. That way the distance calculations are not too far off.

As for your second question, I'd first suggest to update your nodejs and npm to a newer version. If the issue persists, could you open a new ticket please?

**Comment by timbenniks** [comment]
The NPM has package has received an update as well. We are now at version 1.0.4.
